var annotated_dup =
[
    [ "__Allocator", "struct____Allocator.html", "struct____Allocator" ],
    [ "__BlockHeader", "struct____BlockHeader.html", "struct____BlockHeader" ],
    [ "__List", "struct____List.html", "struct____List" ],
    [ "__ListNode", "struct____ListNode.html", "struct____ListNode" ],
    [ "__PQueue", "struct____PQueue.html", "struct____PQueue" ],
    [ "__RLItem", "struct____RLItem.html", "struct____RLItem" ],
    [ "__Vector", "struct____Vector.html", "struct____Vector" ],
    [ "DAC_Tone", "structDAC__Tone.html", "structDAC__Tone" ],
    [ "FunctionWrapper", "structFunctionWrapper.html", "structFunctionWrapper" ],
    [ "InterruptHandlerWrapper", "structInterruptHandlerWrapper.html", "structInterruptHandlerWrapper" ],
    [ "JobWrapper", "structJobWrapper.html", "structJobWrapper" ],
    [ "LCD_BBox", "structLCD__BBox.html", "structLCD__BBox" ],
    [ "LCD_Button", "structLCD__Button.html", "structLCD__Button" ],
    [ "LCD_ButtonLabel", "structLCD__ButtonLabel.html", "structLCD__ButtonLabel" ],
    [ "LCD_Circle", "structLCD__Circle.html", "structLCD__Circle" ],
    [ "LCD_Component", "structLCD__Component.html", "structLCD__Component" ],
    [ "LCD_Coordinate", "structLCD__Coordinate.html", "structLCD__Coordinate" ],
    [ "LCD_Dimension", "structLCD__Dimension.html", "structLCD__Dimension" ],
    [ "LCD_Font", "structLCD__Font.html", "structLCD__Font" ],
    [ "LCD_Image", "structLCD__Image.html", "structLCD__Image" ],
    [ "LCD_Line", "structLCD__Line.html", "structLCD__Line" ],
    [ "LCD_Obj", "structLCD__Obj.html", "structLCD__Obj" ],
    [ "LCD_Padding", "structLCD__Padding.html", "structLCD__Padding" ],
    [ "LCD_Rect", "structLCD__Rect.html", "structLCD__Rect" ],
    [ "LCD_Text", "structLCD__Text.html", "structLCD__Text" ],
    [ "TIMER", "structTIMER.html", "structTIMER" ],
    [ "TIMER_MatchRegister", "structTIMER__MatchRegister.html", "structTIMER__MatchRegister" ],
    [ "TP_ButtonArea", "structTP__ButtonArea.html", "structTP__ButtonArea" ],
    [ "TP_CalibrationMatrix", "structTP__CalibrationMatrix.html", "structTP__CalibrationMatrix" ],
    [ "TP_Coordinate", "structTP__Coordinate.html", "structTP__Coordinate" ]
];