#ifndef __PACMAN_MAZE_H
#define __PACMAN_MAZE_H

// VARIABLES

#define PM_MAZE_SCALED_WIDTH 23
#define PM_MAZE_SCALED_HEIGHT 25
#define PM_MAZE_CELL_SIZE 10

#define PM_MAZE_PIXEL_WIDTH (PM_MAZE_SCALED_WIDTH * PM_MAZE_CELL_SIZE)
#define PM_MAZE_PIXEL_HEIGHT (PM_MAZE_SCALED_HEIGHT * PM_MAZE_CELL_SIZE)

#define PM_WALL_COLOR 0x25283

// TYPES

typedef enum
{
    PM_WALL, // Maze walls
    PM_NONE, // Empty cell, can be traversed if not sorrounded by walls
    PM_PILL, // Normal pill cell
    PM_SUPER_PILL,
    PM_PCMN, // PacMan
    PM_LTPL, // Left portal
    PM_RTPL, // Right portal
    PM_GHS0, // Ghost 0
    PM_GHS1, // Ghost 1
    PM_GHS2, // Ghost 2
} PM_MazeObj;

// MAZE

// clang-format off
PM_MazeObj PM_Maze[PM_MAZE_SCALED_HEIGHT][PM_MAZE_SCALED_WIDTH] = {
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},    
    {PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_WALL, PM_WALL, PM_NONE, PM_WALL, PM_WALL, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_LTPL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_NONE, PM_NONE, PM_WALL, PM_GHS0, PM_GHS1, PM_GHS2, PM_WALL, PM_NONE, PM_NONE, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_RTPL},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_PCMN, PM_NONE, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_NONE, PM_NONE, PM_NONE},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_NONE, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_NONE, PM_NONE, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL, PM_WALL, PM_WALL, PM_PILL, PM_WALL},
    {PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_PILL, PM_WALL},
    {PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL, PM_WALL},
};
// clang-format on

#endif